---
title: "Parameterization and efficient sampling for HMC"
author: "Miao Cai^[Department of Epidemiology and Biostatistics, Saint Louis University. Email address [miao.cai@slu.edu](miao.cai@slu.edu)]"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: readable
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: hide
    highlight: tango
  pdf_document:
    number_sections: yes
link-citations: yes
linkcolor: blue
bibliography: ref.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction to Hamiltonian Monte Carlo (HMC)

## Markov Chain Monte Carlo (MCMC)

Markov Chain calculates the desired posterior distribution by exploring the neighborhoods on which the target probability distribution concentrates. The exploration process is generated by sampling repeatedly from Markov transitions [@betancourt2016diagnosing].

The performance of Markov chain Monte Carlo hinges on how effective these the Markov transitions guide the Markov chains exploring the high density areas [@betancourt2016diagnosing]. When the exploration step is small, we need a lot of simulation to get a holistic picture of the posterior distribution and it is very computationally inefficient. More often in this situation, we don't have sufficient amount of simulations and then get a biased posterior distribution or estimate.



## Hamiltonian Markov Chain Monte Carlo


# References


